version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: agence
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
